description: An Ultima Online shard featuring custom classes, spells, resources and more...

hb:
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  full_width: false # when true, the layout takes full width globally.
  header:
    brand: Zuluhotel Omega # the brand name, leave it empty to use site's title.
    # logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      discord: https://discord.gg/X6TWp76
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: true # when false, remove the color of social icons.
      discord: https://discord.gg/X6TWp76
  blog:
    list_cols_md: 1
    list_cols_lg: 1
    toc:
      position: end
    sidebar:
      sticky: true # set it to false to not stick the sidebar.
      width: .35 # the width of sidebar.
      position: start # the sidebar position: start (left) or end (right).
      profile:
        # title: Profile title other than site title.
        # description: Profile description other than site description.
        avatar_size: 100
        socials:
          discord: https://discord.gg/X6TWp76
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
        style: pills # pills, tabs or underline.
        list_style: slide # slide or vertical.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: HB THEME # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      backgroundImage: '/images/background.jpg'
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts, 0 means disabled.
      pinned_posts_position: "list"
      main_sections: # leave it empty to include all regular pages.
  # gallery:
  #   thumbnail_size: "x640"
  # google_fonts:
    # families:
      # - name: Lato

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Zuluhotel Omega'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 4
          socials:
            discord: https://discord.gg/X6TWp76
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
